### ISSUE TITLE
Use Laravel Naming Convention

### ISSUE THREAD

**Issue by mmikhan** [vardump/optimus#1]
Rename all the controllers, routes, requests class and models to match and follow the Laravel naming convention.
### Example:
- Controller: `HomeController`
- Routes: `Route::get('/', 'HomeController@index')`
- Routes: `Route::get('/api/results', 'ApiController@results')`

> Do not use the convention like `Route::get('/gettwfoll', 'HomeController@index')` as the route doesn't make any sense at all.
- [x] Rename Controllers
- [x] Rename Routes

**Comment by prappo** [comment]
fixed naming convention as much as possible and not conflicted with previous version  . right now it's not possible to rename all controllers  because of many of those controllers linked with others as object . 
check the commit @ https://github.com/vardump/optimus/commit/8c58df32fd1e8bb434c639e0bf31268f80e0af1f

**Comment by mmikhan** [comment]
In this case, leave it for now as it is and follow the convention for all the future Controllers, Routes etc.

**Comment by prappo** [comment]
refactor done . commit @ https://github.com/vardump/optimus/commit/3eeaedb4ab0d79bb17487a1fc26402c9e3907666
